config/routes.rb
Rails.application.routes.draw do
	root 'home#index'	
	get 'order_items/create'
	get 'order_items/update'
	get 'order_items/destroy'
	get 'carts/show'
	#root 'posts#index' #ir a la página de inicio (se establece una sola vez, solo hay un home)
	# resources :posts
	resources :posts do
		resources :comments, only: [:create]
		member do
			patch :publish
		end
	end

	

	get "admin", to: 'admin#index'
	get 'admin/products', to: 'admin#products'

	resources :products, only: [:index, :new, :create]
	resources :subscriptors
	resource :cart, only: [:show]
	resources :order_items, only: [:create, :update, :destroy]
	

	

	# post '/comments/:id_post', to 'comments/create'#ruta que me crea un comenario
	# ---------- Home Routes:
	# get '/home/about', to: 'home#about'

	# get '/home/contact_us', to: 'home#contact_us'

	# get '/home/prices', to: 'home#prices'


	# # ------------ Blog Routes:
	# get 'blog/index', to: 'blog#index'

	# get 'blog/new', to: 'blog#new'

	# get 'blog/show', to: 'blog#show'

	# get 'blog/edit', to: 'blog#edit'


	# #--------------- Admin Routes:
	# get 'admin/index'

	# get 'admin/show'

	#Devise
	devise_for :users

	

	
	#get 'home', to: 'home#index' # evita poner el 'index' en la ruta

	#Rutas sinónimas:
	#get 'home/index'
	#get '/home/hello', to: 'home#hello', as: 'my_alias' #(alias)
	#--------------------------------------
	#get '/home/:name', to: 'home#hello' #pasando parámetro(name) a una nueva vista (hello)

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :title, :content, presence: true


  # scope :published, -> {where(published: true)}
  #scope :popular, -> {where("views > ?", 10)} #suponiendo sí se tiene un atributo "views"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

#El usuario debe estar logueado para editar los detalles (edit method)
before_action :authenticate_user!, except: [:index, :show] 

#El usuario logeado no puede  editar, actualiza ni elminar los posts de otros users
#before_action :validate_user, only: [:edit, :update, :destroy]

before_action :is_admin?, only: [:edit, :update, :destroy] 


def index
  #@user=current_user
  #@posts=Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 2)

  if params[:category].blank?
   @posts=Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 2)
   @jumbotron=true
   @last_post = Post.last
   @shoes_category = Category.find_by(name: "Shoes")
   @last_post_shoes = @shoes_category.posts.last
   @glasses_category = Category.find_by(name: "Glasses")
   @last_post_glasses = @glasses_category.posts.last
 else
  @category_id=Category.find_by(name: params[:category]).id
  @posts = Post.where(category_id: @category_id)
  .order(created_at: :desc)
  .paginate(page: params[:page], per_page: 2)

  @jumbotron=false
end


end

def new

  @post=Post.new
end

def show

  @post=Post.find(params[:id])
  @comments=@post.comments.order(created_at: :desc).paginate(page: params[:page], per_page: 1)

end

def edit
  @post=Post.find(params[:id])
end

def destroy

  post = Post.find(params[:id])
  post.destroy
  flash[:notice]="El post fue eliminado exitosamente"
  redirect_to posts_path
end

def create

  @post = Post.new(post_params)
  @post.user = current_user
  if @post.save

    title= @post.title
    id=@post.id
    users = User.where(role: "user")
    type_user ="User"
    users.each do |user|
      user_email = user.email
      UserNotifierMailer.new_post_notifying(user_email, title, id, type_user).deliver_now
    end

    subscriptors =Subscriptor.all
    type_user ="Subscriptor"
    subscriptors.each do |subscriptor|
      subscriptor_email = subscriptor.email
      UserNotifierMailer.new_post_notifying(subscriptor_email, title, id, type_user).deliver_now
    end

    
    flash[:notice]= "Creado!"
    redirect_to posts_path

  else
    flash[:alert] = "Falló"
    render :new
  end
end


def update
  @post=Post.find(params[:id])
  if @post.update(post_params)
    title= @post.title
    id=@post.id
    users = User.where(role: "user")
    type_user ="User"

    users.each do |user|
      user_email = user.email
      UserNotifierMailer.edit_post_notifying(user_email, title, id, type_user).deliver_now
    end

    subscriptors =Subscriptor.all
    type_user ="Subscriptor"
    subscriptors.each do |subscriptor|
      subscriptor_email = subscriptor.email
      UserNotifierMailer.edit_post_notifying(subscriptor_email, title, id, type_user).deliver_now
    end

    flash[:notice]= "Editado!"
    redirect_to posts_path  
  else
    flash[:alert] = "Falló"
    render :edit
  end
end

def publish
  sleep 2
  @post=Post.find(params[:id])
  @post.update(published_at: Time.zone.now)
end


private

def post_params
  params.require(:post).permit(:user_id, :title, :content, :category_id, :published_at) #solo permite estos datos
  
end


def validate_user
  unless current_user.posts.ids.to_s.include? params[:id]
    redirect_to root_path
    flash[:alert] = "You do not have permissions"
  end
end

def is_admin?
  unless current_user.admin?
    flash[:alert] = "You do not have permissions"
    redirect_to root_path
  end
end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_add_comment.html.erb
<h2>Add Comment</h2>

<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="form-group">
    <label for="">Comment</label>
    <%= f.text_area :comment, class: "form-control" %>
    <br>
    <p>
      <%#= f.submit "Save Comment", class: "btn btn-primary" %>
      <%= f.button "Save Comment", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>Publishing..."} %>
    </p>

  </div>
<% end %>

app/views/posts/_cards.html.erb
<div class="row mb-2">
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-primary"><%= @last_post_shoes.category.name %></strong>
        <h3 class="mb-0">

          <% if @last_post_shoes.title.length > 20%>
          <%= link_to @last_post_shoes.title.truncate(20), post_path(@last_post_shoes.id), class:"text-dark"  %>
          <% else %>
          <%= link_to @last_post_shoes.title.truncate(20), post_path(@last_post_shoes.id), class:"text-dark" %>
          <% end %>

        </h3>
        <div class="mb-1 text-muted"><%= time_ago_in_words( @last_post_shoes.created_at)%> ago</div>
        <p class="card-text mb-auto">
          <% if @last_post_shoes.content.length > 60 %>
          <%= @last_post_shoes.content.truncate(60) %>
          <p class="lead mb-0"><%= link_to "...Read More", post_path(@last_post_shoes.id), class: "font-weight" %></p>
          <% else %>
          <%= @last_post_shoes.content %>
          <% end %>

        </p>
        
      </div>
      <%= image_tag('download.jpeg', class: "card-img-right flex-auto d-none d-md-block")  %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-success"><%= @last_post_glasses.category.name %></strong>
        <h3 class="mb-0">
          <% if @last_post_glasses.title.length > 20%>
          <%= link_to @last_post_glasses.title.truncate(20), post_path(@last_post_glasses.id), class:"text-dark"  %>
          <% else %>
          <%= link_to @last_post_glasses.title.truncate(20), post_path(@last_post_glasses.id), class:"text-dark" %>
          <% end %>
        </h3>
        <div class="mb-1 text-muted"><%= time_ago_in_words( @last_post_glasses.created_at)%> ago</div>
        <p class="card-text mb-auto">
          <% if @last_post_glasses.content.length > 40 %>
          <%= @last_post_glasses.content.truncate(40) %>
          <p class="lead mb-0"><%= link_to "...Read More", post_path(@last_post_glasses.id), class: "font-weight" %></p>
          <% else %>
          <%= @last_post_glasses.content %>
          <% end %>
        </p>

      </div>
      <%= image_tag('download.jpeg', class: "card-img-right flex-auto d-none d-md-block")  %>
    </div>
  </div>
</div>

app/views/posts/_comments.html.erb
<div class="p-3 mb-3 bg-light rounded">
  <h4 class="font-italic" id="comments">Comments</h4>


  <% @comments.each do |comment| %>

    <p class="mb-0">
      <%= comment.user.email %>
      <br>
      <strong>Comment: </strong>
      <%= comment.comment %>
    </p>
    <br>

  <% end %>
  </div>

  <nav class="blog-pagination">
    <%= will_paginate @comments, params: {anchor:"comments"}, previous_label: '&laquo;', next_label: '&raquo;' %>
  </nav>

  

app/views/posts/_form.html.erb
<div class="container">

	<%= render "header" %>

	<div class="nav-scroller py-1 mb-2">
		<nav class="nav d-flex justify-content-between">
			<%= render "nav" %>
		</nav>
	</div>
	<%= render "layouts/alerts" %>
</div>

<main role="main" class="container mt-4">
	<div class="row">
		<div class="col-md-12 blog-main">
			<hr>
			<div class="blog-post">
				<% unless @post.new_record? %>
				<h2 class="blog-post-title"><%= @post.title %></h2>
				<p class="blog-post-meta"><%= time_ago_in_words(@post.created_at) %> ago by <a href="#"><%= @post.user.email %></a></p>
				<% end %>
				<p>
					<%= form_for @post do |f| %>
						<% if @post.errors.any? %>
							<div class="alert alert-danger alert-block alert-fized">
								<p>
									<%= pluralize(@post.errors.count, "error")  %>
									prevented this post from saving
								</p>
								<ul>
									<% @post.errors.full_messages.each do |msg| %>
										<li><%= msg %></li>
									<% end %>
								</ul>
								
							</div>
						<% end %>

					<div class="form-group">
						<label>Category</label>
						<%= f.collection_select(:category_id, Category.all, :id, :name, {prompt:"Choose a Category"}, {class: "form-control"})  %>
					</div>
					<div class="form-group">
						<label for="exampleFormControlInput1">Title</label>
						<%= f.text_field :title, class: "form-control"  %>
					</div>
					<div class="form-group">
						<label for="exampleFormControlTextarea1">Example textarea</label>
						<%= f.text_area :content, class: "form-control" %>
					</div>
					<%  if @post.new_record? %>
					<%= f.button class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>Publishing..."} %>
					<% else %>
					<%= f.button class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>Editing..."} %>
					<% end %>
					<% end %>
				</p>
			</div><!-- /.blog-post -->
		</div><!-- /.blog-main -->
	</div><!-- /.row -->
</main><!-- /.container -->

<%= render "layouts/footer" %>

app/views/posts/_jumbotron.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic"><%= @last_post.title %></h1>
    <p class="lead my-3">
      <% if @last_post.content.length > 140 %>
      <%= @last_post.content.truncate(140) %>
      <p class="lead mb-0"><%= link_to "...Read More", post_path(@last_post.id), class: "text-white font-weight-bold" %></p>
      <% else %>
      <%= @last_post.content %>
      <% end %>
    </p>
  </div>
</div>

<%= render "cards" %>

app/views/posts/_nav.html.erb
      <% Category.all.each do |category| %>
      <%= link_to category.name, posts_path(category: category.name), class: "p-2 text-muted" %>
      <% end %>

app/views/posts/_other.html.erb
<h1>Posts</h1>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to "Crear nuevo post", new_post_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.user.email %></td>
        <td><%= post.title %></td>
        <td>
          <%#= link_to "Texto que va a aparecer", ruta_path, method, class %>
          <%= link_to "Mostrar", post_path(post) %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to "Editar", edit_post_path(post) %>
            <%= link_to "Eliminar", post_path(post), method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<div class="container">

 <%= render "header" %>

 <div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= render "nav" %>
  </nav>
</div>

<%= render "layouts/alerts" %>

<% if @jumbotron %>
<%= render "jumbotron" %>
<% end %>



<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom" id="posts">
        <% if @jumbotron %>
        Index
        <% elsif %>
        Filtered by: <b><%= params[:category] %></b>
        <% end %>
      </h3>

      <% @posts.each do |post| %>
      <div class="blog-post">
        <h2 class="blog-post-title"><%= link_to post.title, post_path(post.id), class: "text-muted", style: "text-decoration: none" %></h2>
        <p class="blog-post-meta"><%= time_ago_in_words(post.created_at) %> ago by <a href="#"><%= post.user.email %></a>
        </p>
        <!-- <small>Category: <%#= Category.find(post.category_id).name %></small> -->
        <small>Category: <%= post.category.name %></small>


        <p>
          <% if post.content.length > 250 %>
          <%= post.content.truncate(250) %>
          <%= link_to "...Read More", post_path(post.id) %>
          <% else %>
          <%= post.content %>
          <% end %>

        </p>
      </div><!-- /.blog-post -->
      <% end %>


      <nav class="blog-pagination">
        <%= will_paginate @posts, params: {anchor:"posts"}, previous_label: '&laquo;', next_label: '&raquo;' %>
        <!-- <a class="btn btn-outline-primary" href="#">Older</a>
          <a class="btn btn-outline-secondary disabled" href="#">Newer</a> -->
        </nav>

      </div><!-- /.blog-main -->

      <aside class="col-md-4 blog-sidebar">
        <div class="p-3 mb-3 bg-light rounded">
          <h4 class="font-italic">About</h4>
          <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        </div>

        <div class="p-3">
          <h4 class="font-italic">Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2014</a></li>
            <li><a href="#">February 2014</a></li>
            <li><a href="#">January 2014</a></li>
            <li><a href="#">December 2013</a></li>
            <li><a href="#">November 2013</a></li>
            <li><a href="#">October 2013</a></li>
            <li><a href="#">September 2013</a></li>
            <li><a href="#">August 2013</a></li>
            <li><a href="#">July 2013</a></li>
            <li><a href="#">June 2013</a></li>
            <li><a href="#">May 2013</a></li>
            <li><a href="#">April 2013</a></li>
          </ol>
        </div>

        <div class="p-3">
          <h4 class="font-italic">Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
        </div>
      </aside><!-- /.blog-sidebar -->

    </div><!-- /.row -->

  </main><!-- /.container -->

  <%= render "layouts/footer" %>
  <script>
    ProductView();
  </script>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/otros.html.erb
<h1>Posts</h1>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to "Crear nuevo post", new_post_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.user.email %></td>
        <td><%= post.title %></td>
        <td>
          <%#= link_to "Texto que va a aparecer", ruta_path, method, class %>
          <%= link_to "Mostrar", post_path(post) %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to "Editar", edit_post_path(post) %>
            <%= link_to "Eliminar", post_path(post), method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/publish.js.erb
$("#published_at").text(" <%= @post.published_at %>");

app/views/posts/show.html.erb
<div class="container">

	<%= render "header" %>

	<div class="nav-scroller py-1 mb-2">
		<nav class="nav d-flex justify-content-between">
			<%= render "nav" %>
		</nav>
	</div>
	<%= render "layouts/alerts" %>
</div>

<main role="main" class="container mt-4">
	<div class="row">
		<div class="col-md-12 blog-main">
			<hr>
			<div class="blog-post">
				<h2 class="blog-post-title"><%= @post.title %></h2>
				<p class="blog-post-meta"><%= time_ago_in_words(@post.created_at) %> ago by <a href="#"><%= @post.user.email %></a>
				</p>
				<small class="blog-post-meta">Category: <%= @post.category.name %> | </small>
				<small class="blog-post-meta">Published at: <span id="published_at"><%= @post.published_at %></span></&nbsp;&nbsp;small>
				<p>
					<% if user_signed_in? && current_user.admin? %>
					<%= link_to "Publish", publish_post_path(@post), method: :patch, remote: true, data:{
						disable_with: "<i class='fa fa-spinner fa-spin'></i>Publishing..."
					},  class: "btn btn-warning"%>
					<%= link_to "Editar", edit_post_path(@post), class: "btn btn-primary" %>
					<%= link_to "Eliminar", post_path(@post), method: :delete, data: {confirm: "Are you sure?", disable_with: "<i class='fa fa-spinner fa-spin'></i>Deleting..."}, class: "btn btn-danger" %>
					<% end %>
				</p>
				<p>
					<%= @post.content %>
				</p>
			</div><!-- /.blog-post -->

			<% if @post.comments.exists? %>
			<%= render 'comments' %>
			<% end %>
			

			<%= render 'add_comment' %>

			<br>

		</div><!-- /.blog-main -->


	</div><!-- /.row -->

</main><!-- /.container -->

<%= render "layouts/footer" %>